[package]
name = "game_2048"
version = "0.1.0"
authors = ["Hampus Sahlin <hampus.sahlin@swiftcourt.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
